application: intern2015-findol
version: 1
runtime: go
api_version: go1

handlers:
- url: /js
  static_dir: js

- url: /template
  static_dir: template

- url: /api/.*
  script: _go_app

- url: /.*
  static_files: template/sample.html
  upload: template/sample.html
